build:
  frontend:
    image: node:6
    commands:
      - cd client
      - npm install
      - npm run build
publish:
  s3:
    acl: public-read
    region: "us-east-1"
    bucket: $$S3_BUCKET
    access_key: $$S3_ACCESS_KEY
    secret_key: $$S3_SECRET_KEY
    source: client/dist
    target: 
    recursive: true
  docker:
    registry: $$DOCKER_REG
    username: $$DOCKER_REG_UN
    password: $$DOCKER_REG_PW
    email: $$DOCKER_REG_EMAIL
    context: server
    repo: igor.im
    tag: latest
    file: Dockerfile
    insecure: false